
name: cI


on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Test with dotnet
        run: dotnet test --configuration Release

      - name: publish with dotnet
        run: dotnet publish H:\Development\My Learning\GithubActions\1.1\src\GitHubActionsDotNet.Api\GitHubActionsDotNet.Api.csproj --configuration Release -o ../publish
  

